// Tests de traducción (web/i18n.js + web/i18n.en.js): un texto nuevo o editado en español no debe
// quedar sin su versión en inglés.
const test = require("node:test");
const assert = require("node:assert/strict");
const { load, read } = require("./load.js");

const files = ["i18n.js", "i18n.en.js"];
const en = load(files, { lang: "en" }).TraceReportsI18n;
const es = load(files, { lang: "es-CL" }).TraceReportsI18n;

test("el idioma sale del navegador", () => {
	assert.equal(en.lang, "en");
	assert.equal(es.lang, "es");
});

test("t() reemplaza variables en los dos idiomas", () => {
	const tpl = "Stub generado por TraceReports a partir de {req} (status {st})";
	const vars = { req: "POST /login", st: 500 };
	assert.equal(es.t(tpl, vars), "Stub generado por TraceReports a partir de POST /login (status 500)");
	assert.equal(en.t(tpl, vars), "Stub generated by TraceReports from POST /login (status 500)");
});

test("t() devuelve el original si no hay traducción", () => {
	assert.equal(en.t("texto que no existe en el diccionario"), "texto que no existe en el diccionario");
});

test("frases exactas conservan los espacios del borde", () => {
	assert.equal(en.t("  Ajustes "), "  Settings ");
});

test("todo tr(\"…\") de tracereports_features.js tiene traducción", () => {
	const src = read("tracereports_features.js");
	const used = [...src.matchAll(/\btr\("((?:[^"\\]|\\.)+)"/g)].map((m) => m[1]);
	assert.ok(used.length > 0);
	for (const s of used) assert.notEqual(en.t(s), s, `sin traducción: "${s}"`);
});

test("los data-tip fijos del botón Mock tienen traducción", () => {
	const src = read("app.js");
	const tips = [...src.matchAll(/data-mock data-tip="([^"$]+)"/g)].map((m) => m[1]);
	assert.ok(tips.length > 0, "no se encontró el data-tip del botón Mock");
	for (const s of tips) assert.notEqual(en.t(s), s, `sin traducción: "${s}"`);
});
